import { FormEvent, useEffect, useState } from 'react';
import { Activity, Award, BriefcaseBusiness, FileText, FolderKanban, GraduationCap, LayoutDashboard, LockKeyhole, LogOut, Menu, Network, Plus, Save, Settings, ShieldCheck, Trash2, UserRound, X } from 'lucide-react';
import { adminApi } from '../services/api';
import { fallbackData } from '../data/fallback';

const modules=[['Dashboard',LayoutDashboard],['Profile',UserRound],['Experience',BriefcaseBusiness],['Education',GraduationCap],['Projects',FolderKanban],['Certifications',Award],['Awards',Award],['Skills',Network],['Social Links',Network],['Resume',FileText],['Documents',FileText],['Site Settings',Settings],['Audit Logs',Activity]] as const;
type AnyRecord=Record<string,unknown>;
export default function AdminApp(){
 const [token,setToken]=useState(()=>sessionStorage.adminToken||'');const [active,setActive]=useState('Dashboard');const [drawer,setDrawer]=useState(false);const [menu,setMenu]=useState(false);const [records,setRecords]=useState<AnyRecord[]>([]);const [notice,setNotice]=useState('');
 const moduleKey=active.toLowerCase().replace(' ','_');
 useEffect(()=>{if(!token||active==='Dashboard')return;adminApi.list<AnyRecord>(moduleKey,token).then(setRecords).catch(e=>setNotice(e.message))},[active,token,moduleKey]);
 const logout=()=>{adminApi.logout(token).catch(()=>{});sessionStorage.removeItem('adminToken');setToken('')};
 if(!token)return <Login onLogin={value=>{sessionStorage.adminToken=value;setToken(value)}}/>;
 const counts={Projects:fallbackData.projects.length,Certifications:fallbackData.certifications.length,Experience:fallbackData.experience.length,Skills:fallbackData.skills.length};
 return <div className="admin-shell"><aside className={menu?'open':''}><div className="admin-brand"><Network/><strong>NetworkPro<small>Portfolio CMS</small></strong><button onClick={()=>setMenu(false)}><X/></button></div><nav>{modules.map(([label,Icon])=><button className={active===label?'active':''} key={label} onClick={()=>{setActive(label);setMenu(false)}}><Icon/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut/> Logout</button></aside><main><header className="admin-header"><button className="admin-menu" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{active}</h1><p>Manage portfolio content and public visibility.</p></div><div className="secure"><ShieldCheck/> Authenticated session</div></header>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}><X/></button></div>}{active==='Dashboard'?<><section className="privacy-banner"><LockKeyhole/><div><strong>Private by default</strong><p>Sensitive fields and documents stay private until you explicitly enable public visibility.</p></div></section><div className="stats">{Object.entries(counts).map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="admin-panel"><h2>Getting started</h2><ol><li>Deploy the Google Apps Script backend.</li><li>Run <code>setupPortfolioSystem()</code>.</li><li>Set the frontend API URL.</li><li>Sign in and review every visibility setting before publishing.</li></ol></section></>:<section className="admin-panel"><div className="panel-heading"><div><h2>{active}</h2><p>{records.length} records</p></div>{!['Audit Logs','Site Settings'].includes(active)&&<button className="button primary" onClick={()=>setDrawer(true)}><Plus/> Add item</button>}</div><div className="table-wrap"><table><thead><tr><th>Title / Name</th><th>Visibility</th><th>Sort order</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{records.length?records.map((record,index)=><tr key={String(record.id||index)}><td>{String(record.name||record.title||record.institution||record.company||'Untitled')}</td><td><span className={`status ${record.visibility==='public'?'public':'private'}`}>{String(record.visibility||'private')}</span></td><td>{String(record.sortOrder||index+1)}</td><td>{String(record.updatedAt||'—')}</td><td><button className="table-action" onClick={()=>setDrawer(true)} aria-label="Edit"><Save/></button><button className="table-action danger" aria-label="Delete"><Trash2/></button></td></tr>):<tr><td colSpan={5}><div className="empty-state">No records returned. Confirm the GAS deployment and create your first item.</div></td></tr>}</tbody></table></div></section>}</main>{drawer&&<EditDrawer module={active} token={token} onClose={()=>setDrawer(false)} onSaved={()=>{setDrawer(false);setNotice('Saved successfully')}}/>}</div>
}
function Login({onLogin}:{onLogin:(token:string)=>void}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await adminApi.login(username,password);onLogin(result.token)}catch(err){setError(err instanceof Error?err.message:'Login failed')}finally{setBusy(false)}}return <main className="login-page"><section className="login-brand"><Network/><h1>NetworkPro</h1><p>Secure portfolio content management.</p></section><form className="login-card" onSubmit={submit}><ShieldCheck/><h2>Admin sign in</h2><p>Credentials are verified by Google Apps Script. Passwords are never stored in the frontend.</p><label>Username or email<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="form-error">{error}</div>}<button className="button primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><a href="#home">Return to portfolio</a></form></main>}
function EditDrawer({module,token,onClose,onSaved}:{module:string;token:string;onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState('');const [visibility,setVisibility]=useState('private');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);await adminApi.save(module.toLowerCase().replace(' ','_'),{name,visibility,sortOrder:999},token);onSaved()}return <div className="drawer-backdrop"><form className="edit-drawer" onSubmit={submit}><header><div><h2>Add {module} item</h2><p>New content is private by default.</p></div><button type="button" onClick={onClose}><X/></button></header><label>Name / title<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Visibility<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="private">Private</option><option value="public">Public</option></select><small>Public content is visible to everyone on the internet.</small></label><label>Sort order<input type="number" defaultValue="999" min="0"/></label><div className="drawer-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}><Save/> {busy?'Saving…':'Save item'}</button></div></form></div>}
